# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-18 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30, verbose_name='姓名')),
                ('upwd', models.CharField(max_length=30, verbose_name='密码')),
                ('uage', models.IntegerField(verbose_name='年龄')),
                ('uemail', models.EmailField(max_length=254, null=True, verbose_name='邮箱')),
                ('isActive', models.BooleanField(default=True, verbose_name='活动用户')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'users',
                'ordering': ['id'],
            },
        ),
    ]
