# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-18 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='uage',
            field=models.IntegerField(null=True, verbose_name='年龄'),
        ),
    ]
