# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-17 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='uphone',
            field=models.CharField(max_length=11, verbose_name='手机号码'),
        ),
    ]
