# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-20 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20190120_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
            ],
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['id'], 'verbose_name': '书籍', 'verbose_name_plural': '书籍'},
        ),
    ]
