# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-20 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20190120_1047'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wife',
            table='wife',
        ),
    ]
