# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-20 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20190120_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wife',
            options={'ordering': ['id'], 'verbose_name': '夫人', 'verbose_name_plural': '夫人'},
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Publisher', verbose_name='对应出版社'),
        ),
    ]
