# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-20 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20190120_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_set',
            field=models.ManyToManyField(to='index.Author'),
        ),
    ]
