# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-16 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_book_author_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wife',
            name='author',
        ),
        migrations.AddField(
            model_name='wife',
            name='author_set',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Author', verbose_name='作者'),
        ),
    ]
